#!/usr/bin/env node

'use strict'

const commander = require('commander')
const fs = require('fs')
const MailDispatcher = require('./src/mail-dispatcher')

const bootstrap = (application, action) => {
    try {
        var configurationFile = application.configuration || __dirname + '/config.json'
        var configuration = JSON.parse(fs.readFileSync(configurationFile))
        var instance = new MailDispatcher(configuration)

        action(instance)
    } catch(err) {
        console.error(err.message || err)
        return process.exit(1)
    }
}

var application = commander
    .version('0.0.1')

application
    .option('-c, --configuration [path]', 'Path to configuration file')

application
    .command('help')
    .description('Prints the application\'s help screen')
    .action(() => {
        application.help()
    })

application
    .command('setup')
    .description('Setup ')
    .action(() => {
        bootstrap(application, (instance) => {
            instance.setup()
        })
    })

application
    .command('deploy')
    .description('Deploy latest version of configuration and function')
    .action(() => {
        bootstrap(application, (instance) => {
            instance.deploy()
        })
    })

application.parse(process.argv)