name: CD

on:
  push:
  pull_request:

env:
  CONFIG: '${{ secrets.CONFIG }}'
  MAPPING: '${{ secrets.MAPPING }}'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2


  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    concurrency: deploy
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        echo "${{ env.CONFIG }}" > config.json
        echo "${{ env.MAPPING }}" > mapping.json
        
    - name: Update Dependencies
      run: npm install

    - name: Setup
      run: ./mail-dispatcher setup

    - name: Cleanup
      run: rm config.json mapping.json